"""Add position_id to Payrolls

Revision ID: 0877e6193f92
Revises: 8f64ebaf955e
Create Date: 2026-01-11 21:12:44.633722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0877e6193f92'
down_revision: Union[str, Sequence[str], None] = '8f64ebaf955e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payrolls', sa.Column('position_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'payrolls', 'positions', ['position_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payrolls', type_='foreignkey')
    op.drop_column('payrolls', 'position_id')
    # ### end Alembic commands ###
