"""Add PublicHoliday model

Revision ID: 19a5baf376a6
Revises: 0877e6193f92
Create Date: 2026-01-11 21:32:33.211846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19a5baf376a6'
down_revision: Union[str, Sequence[str], None] = '0877e6193f92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('public_holidays',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('local_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_public_holidays_date'), 'public_holidays', ['date'], unique=True)
    op.create_index(op.f('ix_public_holidays_id'), 'public_holidays', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_public_holidays_id'), table_name='public_holidays')
    op.drop_index(op.f('ix_public_holidays_date'), table_name='public_holidays')
    op.drop_table('public_holidays')
    # ### end Alembic commands ###
