"""add salary payment batches

Revision ID: ac5a9430d80f
Revises: c33173207169
Create Date: 2026-06-14 07:22:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ac5a9430d80f'
down_revision: Union[str, Sequence[str], None] = 'c33173207169'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("salary_payment_batches",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=False),
        sa.Column("period_start", sa.Date(), nullable=False),
        sa.Column("period_end", sa.Date(), nullable=False),
        sa.Column("payment_date", sa.DateTime(), nullable=False),
        sa.Column("total_amount", sa.Numeric(precision=12, scale=2), nullable=True, server_default="0"),
        sa.Column("status", sa.String(length=20), nullable=True, server_default="draft"),
        sa.Column("payment_method", sa.String(length=20), nullable=True, server_default="bank"),
        sa.Column("payment_reference", sa.String(length=100), nullable=True),
        sa.Column("paid_by", sa.Integer(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"]),
        sa.ForeignKeyConstraint(["paid_by"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table("salary_payment_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("batch_id", sa.Integer(), nullable=False),
        sa.Column("payslip_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("paid_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["batch_id"], ["salary_payment_batches.id"]),
        sa.ForeignKeyConstraint(["payslip_id"], ["payslips.id"]),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("payslips", sa.Column("batch_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        "fk_payslips_batch_id_salary_payment_batches",
        "payslips", "salary_payment_batches",
        ["batch_id"], ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_payslips_batch_id_salary_payment_batches", "payslips", type_="foreignkey")
    op.drop_column("payslips", "batch_id")
    op.drop_table("salary_payment_items")
    op.drop_table("salary_payment_batches")
    # ### end Alembic commands ###
