"""add bonus and monthly work days

Revision ID: 234487108e34
Revises: 19a5baf376a6
Create Date: 2026-01-16 20:28:35.123450

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "234487108e34"
down_revision: str | Sequence[str] | None = "19a5baf376a6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
