"""add_user_details_shift_tolerance_payroll_fields

Revision ID: 26457e1eaad9
Revises: 1ebfca42967f
Create Date: 2026-01-04 20:58:12.519559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26457e1eaad9'
down_revision: Union[str, Sequence[str], None] = '1ebfca42967f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payrolls', sa.Column('monthly_salary', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('shifts', sa.Column('tolerance_minutes', sa.Integer(), nullable=True))
    op.add_column('shifts', sa.Column('break_duration_minutes', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('job_title', sa.String(), nullable=True))
    op.add_column('users', sa.Column('department', sa.String(), nullable=True))
    op.add_column('users', sa.Column('company', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'company')
    op.drop_column('users', 'department')
    op.drop_column('users', 'job_title')
    op.drop_column('shifts', 'break_duration_minutes')
    op.drop_column('shifts', 'tolerance_minutes')
    op.drop_column('payrolls', 'monthly_salary')
    # ### end Alembic commands ###
