"""add_is_manual_to_timelog

Revision ID: 305e512e4a8b
Revises: 656ab3cb1bdc
Create Date: 2026-01-08 19:50:16.734166

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "305e512e4a8b"
down_revision: str | Sequence[str] | None = "656ab3cb1bdc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("timelogs", sa.Column("is_manual", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("timelogs", "is_manual")
    # ### end Alembic commands ###
