"""Add TRZ contract annexes and payment fields

Revision ID: 4df175e9d247
Revises: add_trz_settings
Create Date: 2026-03-14 17:17:54.662318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4df175e9d247'
down_revision: Union[str, Sequence[str], None] = 'add_trz_settings'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contract_annexes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('annex_number', sa.String(length=50), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('base_salary', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('position_id', sa.Integer(), nullable=True),
    sa.Column('work_hours_per_week', sa.Integer(), nullable=True),
    sa.Column('night_work_rate', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('overtime_rate', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('holiday_rate', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('is_signed', sa.Boolean(), nullable=True),
    sa.Column('signed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['employment_contracts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contract_annexes_id'), 'contract_annexes', ['id'], unique=False)
    op.add_column('employment_contracts', sa.Column('payment_day', sa.Integer(), nullable=True))
    op.add_column('employment_contracts', sa.Column('experience_start_date', sa.Date(), nullable=True))
    op.add_column('payslips', sa.Column('payment_status', sa.String(length=20), nullable=True))
    op.add_column('payslips', sa.Column('actual_payment_date', sa.DateTime(), nullable=True))
    op.add_column('payslips', sa.Column('payment_method', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payslips', 'payment_method')
    op.drop_column('payslips', 'actual_payment_date')
    op.drop_column('payslips', 'payment_status')
    op.drop_column('employment_contracts', 'experience_start_date')
    op.drop_column('employment_contracts', 'payment_day')
    op.drop_index(op.f('ix_contract_annexes_id'), table_name='contract_annexes')
    op.drop_table('contract_annexes')
    # ### end Alembic commands ###
