"""add_payroll_models

Revision ID: 5f162677947b
Revises: 8f309b6300c1
Create Date: 2026-01-04 16:25:33.009016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f162677947b'
down_revision: Union[str, Sequence[str], None] = '8f309b6300c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payslips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('total_regular_hours', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_overtime_hours', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('regular_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('overtime_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payslips_id'), 'payslips', ['id'], unique=False)
    op.add_column('payrolls', sa.Column('overtime_multiplier', sa.Numeric(precision=4, scale=2), nullable=True))
    op.add_column('payrolls', sa.Column('standard_hours_per_day', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payrolls', 'standard_hours_per_day')
    op.drop_column('payrolls', 'overtime_multiplier')
    op.drop_index(op.f('ix_payslips_id'), table_name='payslips')
    op.drop_table('payslips')
    # ### end Alembic commands ###
