"""Add currency and annual_leave_days to Payroll

Revision ID: 6488e84c6641
Revises: 29d5806acc09
Create Date: 2026-01-06 22:22:45.018909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6488e84c6641'
down_revision: Union[str, Sequence[str], None] = '29d5806acc09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payrolls', sa.Column('currency', sa.String(), nullable=True))
    op.add_column('payrolls', sa.Column('annual_leave_days', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payrolls', 'annual_leave_days')
    op.drop_column('payrolls', 'currency')
    # ### end Alembic commands ###
