"""add api_key to gateways

Revision ID: 98f50ce22b85
Revises: gateway_tables_001
Create Date: 2026-02-19 21:36:01.760474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98f50ce22b85'
down_revision: Union[str, Sequence[str], None] = 'gateway_tables_001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gateway_heartbeats_id'), table_name='gateway_heartbeats')
    op.add_column('gateways', sa.Column('api_key', sa.String(length=64), nullable=True))
    op.drop_index(op.f('ix_gateways_name'), table_name='gateways')
    op.create_unique_constraint(None, 'gateways', ['api_key'])
    op.add_column('invoice_corrections', sa.Column('number', sa.String(length=50), nullable=False))
    op.add_column('invoice_corrections', sa.Column('type', sa.String(length=20), nullable=False))
    op.add_column('invoice_corrections', sa.Column('date', sa.Date(), nullable=False))
    op.add_column('invoice_corrections', sa.Column('status', sa.String(length=20), nullable=True))
    op.add_column('invoice_corrections', sa.Column('company_id', sa.Integer(), nullable=False))
    op.add_column('invoice_corrections', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('invoice_corrections', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'invoice_corrections', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'invoice_corrections', 'companies', ['company_id'], ['id'])
    op.alter_column('printers', 'gateway_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('printers', 'gateway_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'invoice_corrections', type_='foreignkey')
    op.drop_constraint(None, 'invoice_corrections', type_='foreignkey')
    op.drop_column('invoice_corrections', 'created_at')
    op.drop_column('invoice_corrections', 'created_by')
    op.drop_column('invoice_corrections', 'company_id')
    op.drop_column('invoice_corrections', 'status')
    op.drop_column('invoice_corrections', 'date')
    op.drop_column('invoice_corrections', 'type')
    op.drop_column('invoice_corrections', 'number')
    op.drop_constraint(None, 'gateways', type_='unique')
    op.create_index(op.f('ix_gateways_name'), 'gateways', ['name'], unique=True)
    op.drop_column('gateways', 'api_key')
    op.create_index(op.f('ix_gateway_heartbeats_id'), 'gateway_heartbeats', ['id'], unique=False)
    # ### end Alembic commands ###
