"""add terminal sessions and production task logs

Revision ID: ba71d6763af9
Revises: 98f50ce22b85
Create Date: 2026-02-19 22:26:09.065129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba71d6763af9'
down_revision: Union[str, Sequence[str], None] = '98f50ce22b85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('terminal_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('terminal_id', sa.String(length=100), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('workstation_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('gateway_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['gateway_id'], ['gateways.id'], ),
    sa.ForeignKeyConstraint(['workstation_id'], ['workstations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('production_task_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('production_order_id', sa.Integer(), nullable=True),
    sa.Column('production_task_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('quantity_produced', sa.Integer(), nullable=True),
    sa.Column('scrap_quantity', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['production_order_id'], ['production_orders.id'], ),
    sa.ForeignKeyConstraint(['production_task_id'], ['production_tasks.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['terminal_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('production_task_logs')
    op.drop_table('terminal_sessions')
    # ### end Alembic commands ###
