"""add bonus_amount to payslip

Revision ID: f523b388ae26
Revises: 234487108e34
Create Date: 2026-01-16 20:28:57.990401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f523b388ae26'
down_revision: Union[str, Sequence[str], None] = '234487108e34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payslips', sa.Column('bonus_amount', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payslips', 'bonus_amount')
    # ### end Alembic commands ###
