"""Add TRZ templates tables

Revision ID: fdf892bc6900
Revises: 4df175e9d247
Create Date: 2026-03-15 13:20:43.619367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdf892bc6900'
down_revision: Union[str, Sequence[str], None] = '4df175e9d247'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('annex_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('change_type', sa.String(length=50), nullable=False),
    sa.Column('new_base_salary', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('new_work_hours_per_week', sa.Integer(), nullable=True),
    sa.Column('new_night_work_rate', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('new_overtime_rate', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('new_holiday_rate', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_annex_templates_id'), 'annex_templates', ['id'], unique=False)
    op.create_table('clause_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clause_templates_id'), 'clause_templates', ['id'], unique=False)
    op.create_table('contract_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('contract_type', sa.String(length=50), nullable=False),
    sa.Column('work_hours_per_week', sa.Integer(), nullable=False),
    sa.Column('probation_months', sa.Integer(), nullable=False),
    sa.Column('salary_calculation_type', sa.String(length=20), nullable=False),
    sa.Column('payment_day', sa.Integer(), nullable=False),
    sa.Column('night_work_rate', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('overtime_rate', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('holiday_rate', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('work_class', sa.String(length=10), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contract_templates_id'), 'contract_templates', ['id'], unique=False)
    op.create_table('annex_template_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('change_type', sa.String(length=50), nullable=False),
    sa.Column('new_base_salary', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('new_work_hours_per_week', sa.Integer(), nullable=True),
    sa.Column('new_night_work_rate', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('new_overtime_rate', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('new_holiday_rate', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('change_note', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['annex_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_annex_template_versions_id'), 'annex_template_versions', ['id'], unique=False)
    op.create_table('contract_template_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('contract_type', sa.String(length=50), nullable=False),
    sa.Column('work_hours_per_week', sa.Integer(), nullable=False),
    sa.Column('probation_months', sa.Integer(), nullable=False),
    sa.Column('salary_calculation_type', sa.String(length=20), nullable=False),
    sa.Column('payment_day', sa.Integer(), nullable=False),
    sa.Column('night_work_rate', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('overtime_rate', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('holiday_rate', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('work_class', sa.String(length=10), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('change_note', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['contract_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contract_template_versions_id'), 'contract_template_versions', ['id'], unique=False)
    op.create_table('annex_template_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['annex_templates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['version_id'], ['annex_template_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_annex_template_sections_id'), 'annex_template_sections', ['id'], unique=False)
    op.create_table('contract_template_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['contract_templates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['version_id'], ['contract_template_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contract_template_sections_id'), 'contract_template_sections', ['id'], unique=False)
    op.add_column('contract_annexes', sa.Column('status', sa.String(length=20), nullable=False))
    op.add_column('contract_annexes', sa.Column('template_id', sa.Integer(), nullable=True))
    op.add_column('contract_annexes', sa.Column('change_type', sa.String(length=50), nullable=True))
    op.add_column('contract_annexes', sa.Column('change_description', sa.Text(), nullable=True))
    op.add_column('contract_annexes', sa.Column('signature_requested_at', sa.DateTime(), nullable=True))
    op.add_column('contract_annexes', sa.Column('signed_by_employee', sa.Boolean(), nullable=False))
    op.add_column('contract_annexes', sa.Column('signed_by_employee_at', sa.DateTime(), nullable=True))
    op.add_column('contract_annexes', sa.Column('signed_by_employer', sa.Boolean(), nullable=False))
    op.add_column('contract_annexes', sa.Column('signed_by_employer_at', sa.DateTime(), nullable=True))
    op.add_column('contract_annexes', sa.Column('rejection_reason', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'contract_annexes', 'annex_templates', ['template_id'], ['id'], ondelete='SET NULL')
    op.add_column('employment_contracts', sa.Column('template_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'employment_contracts', 'contract_templates', ['template_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employment_contracts', type_='foreignkey')
    op.drop_column('employment_contracts', 'template_id')
    op.drop_constraint(None, 'contract_annexes', type_='foreignkey')
    op.drop_column('contract_annexes', 'rejection_reason')
    op.drop_column('contract_annexes', 'signed_by_employer_at')
    op.drop_column('contract_annexes', 'signed_by_employer')
    op.drop_column('contract_annexes', 'signed_by_employee_at')
    op.drop_column('contract_annexes', 'signed_by_employee')
    op.drop_column('contract_annexes', 'signature_requested_at')
    op.drop_column('contract_annexes', 'change_description')
    op.drop_column('contract_annexes', 'change_type')
    op.drop_column('contract_annexes', 'template_id')
    op.drop_column('contract_annexes', 'status')
    op.drop_index(op.f('ix_contract_template_sections_id'), table_name='contract_template_sections')
    op.drop_table('contract_template_sections')
    op.drop_index(op.f('ix_annex_template_sections_id'), table_name='annex_template_sections')
    op.drop_table('annex_template_sections')
    op.drop_index(op.f('ix_contract_template_versions_id'), table_name='contract_template_versions')
    op.drop_table('contract_template_versions')
    op.drop_index(op.f('ix_annex_template_versions_id'), table_name='annex_template_versions')
    op.drop_table('annex_template_versions')
    op.drop_index(op.f('ix_contract_templates_id'), table_name='contract_templates')
    op.drop_table('contract_templates')
    op.drop_index(op.f('ix_clause_templates_id'), table_name='clause_templates')
    op.drop_table('clause_templates')
    op.drop_index(op.f('ix_annex_templates_id'), table_name='annex_templates')
    op.drop_table('annex_templates')
    # ### end Alembic commands ###
