def DEFAULT_SETTINGS(company_id: int) -> dict:
    return {
        "retention": {
            "company_id": company_id,
            "raw_profile_days": 90,
            "aggregated_profile_months": 12,
            "recommendation_months": 6,
            "feedback_months": 24,
            "audit_log_months": 36,
            "auto_cleanup_enabled": True,
            "cleanup_schedule": "nightly",
            "anonymize_instead_of_delete": False,
            "updated_by": 1,
        },
        "thresholds": {
            "company_id": company_id,
            "punctuality_warning": 70.0,
            "punctuality_critical": 50.0,
            "efficiency_warning": 60.0,
            "efficiency_critical": 40.0,
            "burnout_warning": 0.6,
            "burnout_critical": 0.8,
            "stress_warning": 0.5,
            "stress_critical": 0.7,
            "engagement_warning": 60.0,
            "engagement_critical": 40.0,
            "probation_multiplier": 1.5,
        },
        "computation": {
            "company_id": company_id,
            "computation_frequency": "nightly",
            "incremental_updates_enabled": True,
            "peer_group_cache_hours": 24,
            "min_data_completeness": 0.6,
            "triggered_alerts_enabled": True,
            "max_triggered_alerts_per_day": 10,
        },
        "weights": {
            "company_id": company_id,
            "burnout_overtime_weight": 0.4,
            "burnout_consecutive_days_weight": 0.3,
            "burnout_leave_usage_weight": 0.2,
            "burnout_productivity_decline_weight": 0.1,
            "efficiency_output_weight": 0.6,
            "efficiency_quality_weight": 0.3,
            "efficiency_timeliness_weight": 0.1,
        },
    }


def DEFAULT_RULES(company_id):
    return [
    {
        "name": "Прекомерно извънредно време",
        "description": "Служител работи >12 часа извънредно за седмица",
        "rule_type": "built_in",
        "is_system": True,
        "is_active": True,
        "shadow_mode": False,
        "company_id": company_id,
        "condition_type": "threshold",
        "condition_config": {
            "metric": "overtime_score",
            "operator": ">",
            "threshold": 12.0,
            "period": "weekly",
        },
        "recommendation_template": {
            "type": "schedule_review",
            "priority": "high",
            "title": "Прекомерно извънредно време",
            "description": "Служителят е работил прекомерно извънредно време през последната седмица.",
            "suggested_action": "Прегледай натоварването и планирай почивка.",
            "explanation": "Извънредното време надвишава допустимия лимит за седмицата.",
        },
        "auto_execute_action": "notification",
        "auto_execute": True,
        "created_by": 1,
    },
    {
        "name": "Риск от прегаряне",
        "description": "Комбиниран риск от прегаряне на база OT, последователни дни и отпуск",
        "rule_type": "built_in",
        "is_system": True,
        "is_active": True,
        "shadow_mode": False,
        "company_id": company_id,
        "condition_type": "composite",
        "condition_config": {
            "logic": "AND",
            "conditions": [
                {"metric": "burnout_risk", "operator": ">", "threshold": 0.7},
                {"metric": "consecutive_work_days", "operator": ">", "threshold": 10},
            ],
        },
        "recommendation_template": {
            "type": "burnout_intervention",
            "priority": "critical",
            "title": "Висок риск от прегаряне",
            "description": "Служителят показва признаци на прегаряне.",
            "suggested_action": "Свържи се със служителя и предложи подкрепа.",
            "explanation": "Комбинацията от висок burnout риск и последователни работни дни е тревожна.",
            "coaching_tips": {
                "approach": "supportive",
                "talking_points": [
                    "Забелязвам че работиш много часове напоследък.",
                    "Как мога да те подкрепя?",
                ],
                "avoid": ["Защо не си тръгваш навреме?", "Трябва да си по-ефективен"],
                "follow_up": "Среща след 1 седмица",
            },
        },
        "auto_execute_action": "notification",
        "auto_execute": True,
        "created_by": 1,
    },
    {
        "name": "Намаляваща ефективност",
        "description": "Ефективността намалява 3 последователни седмици",
        "rule_type": "built_in",
        "is_system": True,
        "is_active": True,
        "shadow_mode": False,
        "company_id": company_id,
        "condition_type": "trend",
        "condition_config": {
            "metric": "efficiency_score",
            "direction": "decreasing",
            "consecutive_periods": 3,
            "min_decline_percent": 5.0,
        },
        "recommendation_template": {
            "type": "performance_review",
            "priority": "medium",
            "title": "Намаляваща ефективност",
            "description": "Ефективността на служителя намалява последователно.",
            "suggested_action": "Проведи среща за преглед на представянето.",
            "explanation": "Трендът показва持续но намаляване на ефективността.",
        },
        "auto_execute_action": None,
        "auto_execute": False,
        "created_by": 1,
    },
    {
        "name": "Финансов стрес",
        "description": "Служител е заявил множество аванси/заеми",
        "rule_type": "built_in",
        "is_system": True,
        "is_active": True,
        "shadow_mode": False,
        "company_id": company_id,
        "condition_type": "threshold",
        "condition_config": {
            "metric": "financial_stress_score",
            "operator": ">",
            "threshold": 0.6,
            "period": "monthly",
        },
        "recommendation_template": {
            "type": "financial_support",
            "priority": "high",
            "title": "Финансов стрес",
            "description": "Служителят показва признаци на финансов стрес.",
            "suggested_action": "Предложи информация за финансови програми на компанията.",
            "explanation": "Множество аванси/заеми могат да индикират финансов стрес.",
        },
        "auto_execute_action": None,
        "auto_execute": False,
        "created_by": 1,
    },
]
